POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "user3",
    "password": "password3"
}
###


GET http://localhost:8080/users?id=mapleaple
Authorization: y0z0sjoup7f
###

GET http://localhost:8080/users?name=sh
Authorization: u2tzuj2rdqm

###
PUT http://localhost:8080/users
Authorization: cawz7dzyid
Content-Type: 'application/json

{
    "name": "NewUsername1",
    "age": "NewUserage",
    "email":"asd@asd.com",
    "workingPosition": "Unemployed"
}

### 
DELETE http://localhost:8080/users?id=mapleaple
Authorization: yvco4i5u5